# Dependencies
markdown:    redcarpet
highlighter: pygments

# Permalinks
permalink:   pretty
relative_permalinks: true

# setup
title: 大象跑了
tagline: 'Just for Fun' 
description: 'sardine2|Just for Fun'  
url: "http://sardine.com"  
baseurl: /


# About/contact
owner: 
  name: "sardine2"
  email: sardine2@gmail.com
  bio: "Just for Fun"


# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown: 
  input:GFM

permalink: pretty
paginate: 8

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : 
  disqus :
      short_name : 

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
